services:
  - type: web
    name: clinvar-extractor-api
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        sync: false
